version: 2
jobs:
  test:
    docker:
      - image: themattrix/tox
    working_directory: ~/comparator
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install coveralls
            pip install tox
      - run:
          name: run tests
          command: |
            tox
            coveralls

workflows:
  version: 2
  comparator:
    jobs:
      - test
