version: 2
jobs:
  test-27: &test-template
    docker:
      - image: circleci/python:2.7
    working_directory: ~/comparator
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python -m venv venv || [[ -d venv ]] || virtualenv venv
            . venv/bin/activate
            make install
            pip install coveralls
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
            coveralls

  test-36:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
  test-37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

workflows:
  version: 2
  comparator:
    jobs:
      - test-27
      - test-36
      - test-37
