version: 2
jobs:
  test-27: &test-template
    docker:
      - image: circleci/python:2.7
    working_directory: ~/comparator
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            make venv
            . venv/bin/activate
            make install
            pip install coveralls
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
            coveralls

  test-36:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
  test-37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

workflows:
  version: 2
  comparator:
    jobs:
      - test-27
      - test-36
      - test-37
